# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: true
dist: trusty

env:
  global:
    secure: "eKrVke/ADx4sk12R6OMmHQwu0PRehqbU1oo/l+d4sEwVmP7fsTQa2LEsbWQ8cSrAOSJRnfyCor6MpFNHX5XqPkb/lqhZEFEuy+M8Y1L4Mi3J3EsXqv4IbAerPahOACLdsZgqpfjk8eFHUFr5TpH3JTKPfRd4SaWL/YQKQHVUKjoTDFVCoqIr/qH5OxyS3EGAj2w3KKWUt068rsKlVllose41HI/YiGSWrmjqnGcr5jTcZXCnNhPsaL6Rqm99vkEygfA93LC2Yy7Zc/RHdmiJXqCPmgusidAWROl3U/o1LlQ0LkJE2arvJ4gj8BVBTyVPOzxLETDo6oyNzfwx7IGr1/eGIhIGOyxEgY3sRPpWN1mR8PJRCyuBD5YHHKqPJfEayJEoxrsg/VBPKFJJNUnz/FI6n+Lg1bw+hy3xsS9bpOXPC4bdDbxDkvAbKtbJK1PuCGIc9Fcrxae4X1Fo+Rm/4ft7BWIhaT8pwZ6wBRJo2bskzVYZLezCGJDhp0LM5cqxiwiDYgZ8c1H8vdDMIDxoLLEqs1HIit0I6H9DKZo9ys7W6FNac3QIVJGyAXP9NkvCWmYvmy8yLJ1bbPVlW54KMQpQ4hx1f3jifdoA5W0c4UQOk9R7r7Q6e9VnwTIziqQ2PxBE8I21d2Pehyen+cA5ZytZDNxtf1VaL5BhLcfvLqM=" 
matrix:
  include:
    - python: 2.7
      env:
        - TESTMODE=fast
        - REFGUIDE_CHECK=1
        - COVERAGE=
#        - NPY_RELAXED_STRIDES_CHECKING=1
#        - NUMPYSPEC="--upgrade git+git://github.com/numpy/numpy.git@v1.10.2"
        - NUMPYSPEC="numpy==1.11.0"
        - USE_WHEEL=1
      addons:
        apt:
          packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - libgmp-dev
            - libmpfr-dev
            - ccache
            - libfreetype6-dev
            - libpng-dev
            - zlib1g-dev
            - texlive-fonts-recommended
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache:
  directories:
    - $HOME/.ccache
before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - "dpkg -l | grep 'openblas\\|atlas\\|lapack'"
  - "update-alternatives --get-selections | grep 'blas\\|lapack'"
  - mkdir builds
  - pushd builds
  # Install gmpy2 dependencies
  - mkdir -p $HOME/.local
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - pushd mpc-1.0.2
  - ./configure --prefix=$HOME/.local
  - make
  - make install
  - popd
  - export CPATH=$HOME/.local/include
  - export LIBRARY_PATH=$HOME/.local/lib
  # End install gmpy2 dependencies
  # Speed up install by not compiling Cython
  - travis_retry pip install --install-option="--no-cython-compile" Cython==0.22
  - travis_retry pip wheel -w ../wheelhouse --no-deps $NUMPYSPEC
  - pip install --use-wheel --no-index --find-links=../wheelhouse --upgrade numpy
  - travis_retry pip install nose mpmath argparse Pillow
  - travis_retry pip install gmpy2  # speeds up mpmath (scipy.special tests)
  - if [ "${TESTMODE}" == "full" ]; then pip install coverage; fi
  - if [ "${USE_WHEEL}" == "1" ]; then pip install wheel; fi
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        travis_retry pip install matplotlib Sphinx==1.2.3
    fi
  - python -V
  - popd
  - set -o pipefail
script:
  - python -c 'import numpy as np; print("relaxed strides checking:", np.ones((10,1),order="C").flags.f_contiguous)'
  # Make sure that relaxed strides checking is actually in effect; otherwise fail loudly
  - if [ "$NPY_RELAXED_STRIDES_CHECKING" == "1" ]; then python -c'import numpy as np; assert np.ones((10,1),order="C").flags.f_contiguous'; fi
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        # pip wheel . -v
        python setup.py bdist_wheel
        # pip install wheelhouse/* -v
        pip install dist/*whl
        USE_WHEEL_BUILD="--no-build"
    fi
  - python -u $OPTIMIZE runtests.py -g -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD |& tee runtests.log
  - tools/validate_runtests_log.py $TESTMODE < runtests.log
  - if [ "${REFGUIDE_CHECK}" == "1" ]; then python runtests.py -g --refguide-check; fi
notifications:
  # Perhaps we should have status emails sent to the mailing list, but
  # let's wait to see what people think before turning that on.
  email: false
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "dist/scipy-0.17.0-cp27-none-linux_x86_64.whl"
    - "wheelhouse/numpy-1.11.0-cp27-none-linux_x86_64.whl"
  skip_cleanup: true
  on:
    tags: true
